# Generated by Django 5.0.3 on 2024-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkentry',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
