name: frontend451
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  intl: ^0.19.0
  telephony: ^0.2.0
  permission_handler: ^11.3.1
  android_intent: ^2.0.2
  android_intent_plus: ^1.0.0
  cached_network_image: ^3.1.0
  http: ^0.13.3
  wifi_info_flutter: ^2.0.2
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/
